---

name: 🧪 Tests

on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
      - "chore/*"
      - "refactor/*"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_call:


jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.24'
          - '1.25'

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Run tests
        run: go test -v ./... -covermode=count -coverpkg=github.com/nentgroup/viaplay-hateoas-go

  commitlint:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "1.26"
          cache: true
      - name: Install commitlint
        run: go install github.com/conventionalcommit/commitlint@latest

      - name: Lint PR title (for squash merges)
        if: github.event_name == 'pull_request'
        run: echo "$PR_TITLE" | commitlint lint

      - name: Lint last commit message (for direct pushes)
        if: github.event_name == 'push'
        run: git log -1 --pretty=format:"%s" | commitlint lint
